CREATE TABLE [dbo].[Post]
(
	[Id] UNIQUEIDENTIFIER NOT NULL, 
    [Heading] NVARCHAR(1024) NOT NULL, 
    [Message] NVARCHAR(MAX) NOT NULL, 
    [Email] NVARCHAR(1024) NOT NULL, 
    [Date] DATETIME NOT NULL,
	CONSTRAINT [PK_Post] PRIMARY KEY CLUSTERED ([Id] ASC)
)
